### ISSUE TITLE
Invalid target for disableBedTooFarWarning.ServerPlayerEntityMixin#shouldBypassWarning()

### ISSUE THREAD

**Issue by sternschnaube** [axialeaa/DoormatCarpetExtension#6]
Seems to be related with Raknetify, but not sure.

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'raknetify'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'raknetify'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: java.lang.ExceptionInInitializerError
	at com.ishland.raknetify.fabric.RaknetifyFabric.onPreLaunch(RaknetifyFabric.java:98) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.<clinit>(MultiVersionUtil.java:122) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.RaknetifyFabric.onPreLaunch(RaknetifyFabric.java:98) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3473) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2542) ~[?:?]
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.tryLocateFields(MultiVersionUtil.java:133) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.<clinit>(MultiVersionUtil.java:62) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.RaknetifyFabric.onPreLaunch(RaknetifyFabric.java:98) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3473) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2542) ~[?:?]
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.tryLocateFields(MultiVersionUtil.java:133) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.<clinit>(MultiVersionUtil.java:62) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.RaknetifyFabric.onPreLaunch(RaknetifyFabric.java:98) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method shouldBypassWarning(Z)Z in doormat.mixins.json:rule.disableBedTooFarWarning.ServerPlayerEntityMixin from mod doormat failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap doormat-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3473) ~[?:?]
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2542) ~[?:?]
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.tryLocateFields(MultiVersionUtil.java:133) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.common.util.MultiVersionUtil.<clinit>(MultiVersionUtil.java:62) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at com.ishland.raknetify.fabric.RaknetifyFabric.onPreLaunch(RaknetifyFabric.java:98) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.11.jar:?]
	... 4 more

**Comment by axialeaa** [comment]
seems to be related to a mixin conflict of ServerPlayerEntity. looking into a solution and hopefully pushing a fix soon!

**Comment by venaminecraft** [comment]
Great, thanks 😄

**Comment by axialeaa** [comment]
it is not in fact related to raknetify. one of my mixins had an invalid target, funnily enough because i recently changed the target on fabric's end! i just forgot to update it here.

it does mean that i'm gonna have to get this fix pushed as quickly as possible, since it's an issue for everybody and not just raknetify users

**Comment by venaminecraft** [comment]
Thanks for the fix!

**Comment by axialeaa** [comment]
if all goes well, i'll push it tomorrow. definitely this week
