### ISSUE TITLE
Erroneous remap = false in ItemEnchantmentsComponentMixin#cycleLine target, causing a crash

### ISSUE THREAD

**Issue by sternschnaube** [axialeaa/DoormatCarpetExtension#7]
Mixin apply for mod doormat failed doormat.mixins.json:rule.compactEnchantTooltips.ItemEnchantmentsComponentMixin from mod doormat -> net.minecraft.class_9304: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on cycleLine could not find any targets matching 'appendTooltip' in net.minecraft.class_9304. Using refmap doormat-refmap.json [PREINJECT Applicator Phase -> doormat.mixins.json:rule.compactEnchantTooltips.ItemEnchantmentsComponentMixin from mod doormat -> Prepare Injections ->  -> handler$djl000$doormat$cycleLine(Lnet/minecraft/class_1792$class_9635;Ljava/util/function/Consumer;Lnet/minecraft/class_1836;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on cycleLine could not find any targets matching 'appendTooltip' in net.minecraft.class_9304. Using refmap doormat-refmap.json [PREINJECT Applicator Phase -> doormat.mixins.json:rule.compactEnchantTooltips.ItemEnchantmentsComponentMixin from mod doormat -> Prepare Injections ->  -> handler$djl000$doormat$cycleLine(Lnet/minecraft/class_1792$class_9635;Ljava/util/function/Consumer;Lnet/minecraft/class_1836;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_9334.method_57899(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.method_57906(class_9334.java:272) [server-intermediary.jar:?]
	at net.minecraft.class_9334.<clinit>(class_9334.java:92) [server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:189) [server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:179) [server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:96) [server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:12) [server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:44) [server-intermediary.jar:?]
	at net.minecraft.class_3962.method_17758(class_3962.java:69) [server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
[07:42:37] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:189) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_3962.method_17758(class_3962.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_9304 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_9334.method_57899(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.method_57906(class_9334.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.<clinit>(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:189) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_3962.method_17758(class_3962.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_9334.method_57899(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.method_57906(class_9334.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.<clinit>(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:189) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_3962.method_17758(class_3962.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [doormat.mixins.json:rule.compactEnchantTooltips.ItemEnchantmentsComponentMixin from mod doormat] from phase [DEFAULT] in config [doormat.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_9334.method_57899(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.method_57906(class_9334.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.<clinit>(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:189) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_3962.method_17758(class_3962.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on cycleLine could not find any targets matching 'appendTooltip' in net.minecraft.class_9304. Using refmap doormat-refmap.json [PREINJECT Applicator Phase -> doormat.mixins.json:rule.compactEnchantTooltips.ItemEnchantmentsComponentMixin from mod doormat -> Prepare Injections ->  -> handler$djl000$doormat$cycleLine(Lnet/minecraft/class_1792$class_9635;Ljava/util/function/Consumer;Lnet/minecraft/class_1836;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_9334.method_57899(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.method_57906(class_9334.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_9334.<clinit>(class_9334.java:92) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_57350(class_1792.java:189) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792$class_1793.method_58406(class_1792.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_1792.<init>(class_1792.java:96) ~[server-intermediary.jar:?]
	at net.minecraft.class_1739.<init>(class_1739.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_3962.method_17758(class_3962.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more

**Comment by axialeaa** [comment]
girl can't catch a break

**Comment by axialeaa** [comment]
i have not been able to reproduce the issue, but i've made a change i suspect could fix it

**Comment by venaminecraft** [comment]
I'm running your mod against ~150. A good compatible sign soon 😄

**Comment by axialeaa** [comment]
ah, i would always recommend checking if a bug is present in a minimum-reproducible environment first if possible. otherwise you may accidentally attribute the cause of the bug to doormat instead of another mod

**Comment by venaminecraft** [comment]
I check one by one. Problem solved with Doormat disabled.
Seems to be some conflict.

**Comment by venaminecraft** [comment]
You can pass me early builds, I can check if the problem still occurs.

**Comment by axialeaa** [comment]
uploaded a pre-release just now. if the issue is fixed on your end, i'll publish it as version 1.1.2.

**Comment by venaminecraft** [comment]
Thanks. A new error: https://pastebin.com/raw/sqgDFzdL

**Comment by axialeaa** [comment]
would you mind opening a new issue for that, just so i can refer to it in the changelog? i've already fixed it lol
